config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :mates
 
  #get 'home/index'
  get 'home/about'
   get 'home/rules'
  root 'home#index'
  #root 'mates#index'
  
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mate.rb
class Mate < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :mates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def rules
  end
end

app/controllers/mates_controller.rb
class MatesController < ApplicationController
  before_action :set_mate, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  

  # GET /mates or /mates.json
  def index
    @mates = Mate.all
  end

  # GET /mates/1 or /mates/1.json
  def show
  end

  # GET /mates/new
  def new
    #@mate = Mate.new
    @mate = current_user.mates.build
  end

  # GET /mates/1/edit
  def edit
  end

  # POST /mates or /mates.json
  def create
    #@mate = Mate.new(mate_params)
     @mate = current_user.mates.build(mate_params)

    respond_to do |format|
      if @mate.save
        format.html { redirect_to mate_url(@mate), notice: "Mate was successfully created." }
        format.json { render :show, status: :created, location: @mate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mates/1 or /mates/1.json
  def update
    respond_to do |format|
      if @mate.update(mate_params)
        format.html { redirect_to mate_url(@mate), notice: "Mate was successfully updated." }
        format.json { render :show, status: :ok, location: @mate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mates/1 or /mates/1.json
  def destroy
    @mate.destroy

    respond_to do |format|
      format.html { redirect_to mates_url, notice: "Mate was successfully deleted." }
      format.json { head :no_content }
    end
  end

    def correct_user
    @mate = current_user.mates.find_by(id: params[:id])
    redirect_to mates_path, notice: "Not Authorized To Edit This Mate" if @mate.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mate
      @mate = Mate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mate_params
      params.require(:mate).permit(:name, :phone, :email, :location, :level_of_play, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mates_helper.rb
module MatesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
   <%= image_tag("logo.jpg", class: "d-inline-block align-text-top logo ms-4" ) %>
  <%= link_to 'Tennis Mate', root_path, class:"navbar-brand ms-1" %>
  <div class="container-fluid">
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        

        <li class="nav-item">
          <%= link_to 'See tennis mates list', mates_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'About us', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Rules and Etiquettes', home_rules_path, class:"nav-link" %>
        </li>

       
      </ul>
          <div class="d-flex">  
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add mate", new_mate_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>
      </ul>
      </div>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="about">

<h1>About us</h1>
	</br>
	<h3>We're on a mission </h3></br></br>

	<h3> The #1 reason people quit tennis is because they don’t have someone to play with. Our goal	 is to grow tennis by making it easier to get practice, matches, and lessons on your local courts. </h3></br></br>
	<h3> Join our community to meet evenly-matched local players. Always have someone to practice with and compete in our fun and flexible Bracket Challenge League for regular matchplay. </h3></br></br>
		
	<h3> Please sign up and have access to the Tennis Mate world! </h3></br></br>	


</div>

app/views/home/index.html.erb
<body>
<div class="index">

	<h1>Welcome</h1>
		</br>
	<h3>Looking for practice partners, matches, lessons and leagues on your local tennis courts? </h3></br></br></br>

	<h3> We offer you a list of tennis mates to choose from. All levels of play from beginner to advanced and various locations. </h3></br></br>
		
	<h3> Please sign up to have access to the Tennis Mate world! </h3></br></br>	

	<h3> Happy hitting! </h3>

</div>
</body>

app/views/home/rules.html.erb
<div class="about">

<h1>Rules and Ettiquetes</h1>
	</br>
	<h1>IMPORTANT TO NOTE FOR ALL PLAYERS</h1></br></br>

	<h4>1. Matches are self-umpired and should be conducted in the spirit of fair play. <p>

2. No one at this site or connected with the League can take responsibility for the safety or security of players whether playing on the courts or in the facilities associated with the Leagues, or elsewhere.<p>

3. Players compete at their own risk and it is the player's responsibility to ensure any courts used are safe for play.<p>

4. Players are solely responsible for court hire and equipment provision.<p>

5. Players must be 18 or older on the start day of a Round.<p>

6. Players must register and play under their real name (specifically not an alias, pseudonym or nickname) and must provide accurate contact details.<p>

7. We expect players to be sporting and courteous in dealings with opponents, tennis centres and their officials and us as organisers and our partner organisations, and we reserve the right to remove players who are not. </h4></br></br>

	<h6> All code misconducts are analyzed and can result in exclussion from the Tennis Mate Community. </h6></br></br>
		
	<h3> Please sign up and have access to the Tennis Mate world! </h3></br></br>	


</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <title>Tennis Mate</title>  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
    </br>
      <% if notice %>
      <%= render 'layouts/alerts' %>
      <% end %>
      </br>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/mates/_form.html.erb
<%= form_with(model: mate) do |form| %>
  <% if mate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mate.errors.count, "error") %> prohibited this mate from being saved:</h2>

      <ul>
        <% mate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field form-group">
    <% form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Full Name" %>
  </div>
</br>
  <div class="field form-group">
    <% form.label :phone %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>
</br>
  <div class="field form-group">
    <% form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
</br>
  <div class="field form-group">
    <% form.label :location %>
    <%= form.text_field :location, class:"form-control", placeholder:"Location" %>
  </div>
</br>
  <div class="field form-group">
    <% form.label :level_of_play %>
    <%= form.text_field :level_of_play, class:"form-control", placeholder:"Level of Play" %>
  </div>
</br>
    <div class="field form-group">
    
    <%= form.number_field :user_id, id: :mate_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>


</br>
  <div>
    <%= form.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/mates/_mate.html.erb
  <table>
<div id="<%= dom_id mate %>">

  <p>
    <strong>Name:</strong>
    <%= mate.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= mate.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= mate.email %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= mate.location %>
  </p>

  <p>
    <strong>Level of play:</strong>
    <%= mate.level_of_play %>
  </p>
</div>
</table>

app/views/mates/edit.html.erb
<h1>Editing mate</h1>

<%= render "form", mate: @mate %>

<br>

<div>
  
  <%= link_to "Show this mate", @mate, class:"btn btn-info" %> |
  <%= link_to "Back to mates", mates_path, class:"btn btn-dark" %>
  </div>

app/views/mates/index.html.erb
<% if user_signed_in? %>
<h1>List of tennis mates</h1></br>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr class="table-dark">
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Location</th>
      <th>Level of play</th>
    
    </tr>
  </thead>

  <tbody>
    <% @mates.each do |mate| %>
    
          <tr>
        <td><%= link_to mate.name, mate %></td>
        <td><%= mate.phone %></td>
        <td><%= mate.email %></td>
        <td><%= mate.location %></td>
        <td><%= mate.level_of_play %></td>
      </tr>
    
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New mate", new_mate_path, class:"btn btn-success" %>

<% else %>

<body>
<div class="index">

  <h1>List of tennis mates</h1></br>
    </br>

  <h3> Please sign up or sign in to have access to the Tennis Mate world! </h3></br></br> 

  <h3> Happy hitting! </h3>

</div>
</body>

<% end %>

app/views/mates/new.html.erb
<h1>Add new mate</h1>
</br>
<%= render "form", mate: @mate %>

<br>

<div>
  <%= link_to "Back to mates", mates_path, class:"btn btn-dark" %>
</div>

app/views/mates/show.html.erb
<div class="container-fluid bg-dark text-light p-5">
    <div class="container bg-dark p-5">
          <h2 class="display-4">
    <%= @mate.name %>
  </h2>
        <hr>
        <p class="lead">
    <%= @mate.phone %> |
    <%= @mate.email %>  | 
    <%= @mate.location %>  |  
    <%= @mate.level_of_play %>

  </p>
  <br/>
    <%= link_to 'Edit', edit_mate_path(@mate), class:"btn btn-success" %>
  
    <%= link_to 'Back', mates_path, class:"btn btn-primary" %> </br></br>

    <%= button_to 'Delete', @mate, :method=>  :delete, class: "btn btn-danger" %>
    </div>
</div>